#! /bin/sh

# workspaces
bspc monitor -d I II III IV V

#other stuff
bspc config border_width              3
bspc config window_gap                20
bspc config split_ratio               0.6
bspc config pointer_motion_interval   7
bspc config focused_border_color      "#88c0d0"
bspc config normal_border_color       "#4c566a"

# autostart?
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xrandr --output HDMI-0 --mode 2560x1440 --rate 143.91 &
xsetroot -cursor_name left_ptr &
feh --bg-fill --geometry +0-0 $HOME/Pictures/Wallpapers/mountainssss.jpg

# start polybar
$HOME/.config/polybar/launch.sh
